### ISSUE TITLE
Build radar data processing base docker 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/lifewatch-notebooks#2]
Get the code form https://gitlab.com/BerendWijers/radar_cluster and build docker base image

**Comment by skoulouzis** [comment]
We needed the tools package from the radar cluster. They are built as  tar and we need to copy them to docker and build

**Comment by skoulouzis** [comment]
Got error QCDIS/lifewatch-notebooks#1

**Comment by skoulouzis** [comment]
We try to build a base image with vol2bird https://github.com/QCDIS/NaaVRE/issues/112.
Using this image: https://github.com/QCDIS/NaaVRE/blob/c734bdf2c8f5fbf462d4c316259eb1f6df0c928d/docker/Dockerfile-vol2bird 
We get an error: 

```
Installing iris2odim....Cloning into 'iris2odim'...
Already up to date.
Note: switching to '376ae90cf93baafe225e4d394f634fd178e9a238'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 376ae90 added a comment
fatal: No names found, cannot describe anything.
IRIS2ODIM is at version: 376ae90cf93baafe225e4d394f634fd178e9a238
./setup: 401: patch: not found
(RAVE) Could not patch system for building
The command '/bin/bash -o pipefail -c ./setup install' returned a non-zero code: 127
```

**Comment by BerendWijers** [comment]
Is this done by the vol2bird installer?

**Comment by skoulouzis** [comment]
> Is this done by the vol2bird installer?

Yes, following  https://github.com/adokter/vol2birdinstall

**Comment by BerendWijers** [comment]
Ok, I havent tried the same myself. Could you let me know what OS the container has that you are attempting to install it in?

Edit:
There's a prefab docker image, I'm not sure if that would be of help?

https://github.com/adokter/vol2bird/tree/master/docker

**Comment by skoulouzis** [comment]
> 's a prefab docker image, I'm not sure if that would be of help?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by BerendWijers** [comment]
Okay, so I've not used the installer previously (It's rather new). Perhaps we can make an issue at their git? You probably know your setup better than I do. Adriaan Dokter (Maintainer) should be quite responsive.

**Comment by BerendWijers** [comment]
Considering we havent heard anything from Adokter about the fix for the vol2bird installer yet, would it be worthwhile to get the vol2bird docker container running?

**Comment by skoulouzis** [comment]
> Ok, I havent tried the same myself. Could you let me know what OS the container has that you are attempting to install it in?
> 
> Edit: There's a prefab docker image, I'm not sure if that would be of help?
> 
> https://github.com/adokter/vol2bird/tree/master/docker

Looks like with a few tweaks we can install vol2bird using this Dockerfile

**Comment by skoulouzis** [comment]
Jupyter Docker image is built: https://hub.docker.com/repository/docker/qcdis/n-a-a-vre-vol2bird
